[project]
name = "tutor-grammar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=2.1.0",
    "streamlit>=1.43.2",
    "streamlit-lottie>=0.0.5",
]
